// download.js — generates plan.md and triggers browser download

function generatePlanMarkdown(plan) {
  var lines = [
    '# Improvement Plan',
    '',
    '## Goal',
    plan.goal,
    '',
    '## Timeline',
    plan.timeline,
    '',
    '## Skills to Learn',
    plan.skills.map(function (s) { return '- ' + s; }).join('\n'),
    '',
    '## Projects to Build',
    plan.projects.map(function (p) { return '- ' + p; }).join('\n'),
    '',
    '## Resources',
    plan.resources.map(function (r) { return '- ' + r; }).join('\n'),
    '',
    '---',
    '_Generated by CV.Screen_',
  ];

  return lines.join('\n');
}

function triggerDownload(filename, content) {
  var blob = new Blob([content], { type: 'text/markdown' });
  var url  = URL.createObjectURL(blob);
  var a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadPlan(plan) {
  var md = generatePlanMarkdown(plan);
  triggerDownload('plan.md', md);
}