// download.js — exports the chat conversation as a .md file

function generateChatMarkdown(history) {
  var lines = ['# Career Strategy Chat', ''];
  history.forEach(function (m) {
    lines.push(m.role === 'user' ? '## You' : '## Assistant');
    lines.push('');
    lines.push(m.content);
    lines.push('');
  });
  lines.push('---');
  lines.push('_Generated by CV.Screen_');
  return lines.join('\n');
}

function triggerDownload(filename, content) {
  var blob = new Blob([content], { type: 'text/markdown' });
  var url  = URL.createObjectURL(blob);
  var a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function downloadChat() {
  if (!chatHistory.length) return;
  triggerDownload('career-chat.md', generateChatMarkdown(chatHistory));
}
